"use client"

import { useState } from "react"
import { useSearchParams } from "next/navigation"
import { ArrowUp, Bot } from "lucide-react"
import { cn } from "@/lib/utils"

export default function AssistantScreen(){ const params = useSearchParams(); const topic = params.get("topic") || "general"; const [input, setInput] = useState(""); const [messages, setMessages] = useState([{ role:'assistant', content:'👋 Welcome to Ztake AI Assistant — production demo. Ask a question.' }]); function pushAssistant(t){ setMessages(m=>[...m,{role:'assistant',content:t}]) } function pushUser(t){ setMessages(m=>[...m,{role:'user',content:t}]) }

async function sendMessage(){ if(!input.trim()) return; const q = input.trim(); pushUser(q); setInput(''); setMessages(prev=>[...prev,{role:'assistant',content:'...'}]); try{ const res = await fetch('/api/chat/stream',{ method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ question: q, userId: null }) }); if(!res.ok){ const err = await res.json(); setMessages(prev=>{ const copy = prev.slice(0,-1); return [...copy,{role:'assistant',content:'Error: '+(err.error||'unknown')}] }); return } const reader = res.body.getReader(); const decoder = new TextDecoder(); let done=false; let assistantText=''; while(!done){ const { value, done: readerDone } = await reader.read(); if(readerDone){ done=true; break } const chunk = decoder.decode(value, { stream: true }); assistantText += chunk; setMessages(prev=>{ const copy = prev.slice(0,-1); return [...copy,{role:'assistant',content:assistantText}] }); } await fetch('/api/log',{ method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ question: q, answer: assistantText }) }); }catch(e){ console.error(e); setMessages(prev=>{ const copy = prev.slice(0,-1); return [...copy,{role:'assistant',content:'Failed to reach chat server.'}] }); } }

function handleKey(e){ if(e.key==='Enter') sendMessage() }

return (<div className="min-h-screen flex flex-col bg-[#0D0D0F] text-white"> <header className="px-6 py-4 border-b border-white/10 flex items-center justify-between"> <div className="flex items-center"> <Bot className="w-6 h-6 text-primary mr-3"/> <h1 className="text-xl font-semibold">Ztake AI Assistant (Production)</h1> </div> </header> <main className="flex-1 overflow-y-auto p-6 space-y-4"> {messages.map((m,i)=>( <div key={i} className={cn('flex items-start max-w-3xl', m.role==='user'?'ml-auto':'mr-auto')}> <div className={cn('rounded-2xl px-4 py-3 whitespace-pre-wrap', m.role==='assistant'?'bg-white/10':'bg-primary text-black')}> {m.content} </div> </div> ))} </main> <footer className="border-t border-white/10 p-4"> <div className="max-w-4xl mx-auto flex items-center space-x-3"> <input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={handleKey} className="flex-1 bg-white/5 border border-white/10 rounded px-4 py-3" placeholder="Ask about integrations, UPI, payouts..." /> <button onClick={sendMessage} className="px-4 py-3 bg-primary text-black rounded"><ArrowUp className="w-4 h-4"/></button> </div> </footer> </div>) }
